# Generated by Django 3.1.6 on 2021-05-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_auto_20210506_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Grade'},
        ),
    ]
