# Generated by Django 3.1.6 on 2021-05-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_auto_20210507_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'Exam paper', 'verbose_name_plural': 'Exam paper'},
        ),
    ]
