# Generated by Django 3.1.6 on 2021-05-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_auto_20210507_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Question Bank', 'verbose_name_plural': 'Question Bank'},
        ),
    ]
