# Generated by Django 3.1.6 on 2021-05-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_auto_20210507_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('Maths and Computer Science', 'Maths and Computer Science'), ('BioChemistry', 'BioChemistry'), ('Accounting', 'Accounting'), ('Economics', 'Economics'), ('History', 'History'), ('Microbiology', 'Microbiology'), ('Mass Commuication', 'Mass Commuication'), ('International Relations', 'International Relations'), ('Criminology', 'Criminology'), ('Language and Linguistics', 'Language and Linguistics')], default='', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.CharField(choices=[('Maths and Computer Science', 'Maths and Computer Science'), ('BioChemistry', 'BioChemistry'), ('Accounting', 'Accounting'), ('Economics', 'Economics'), ('History', 'History'), ('Microbiology', 'Microbiology'), ('Mass Commuication', 'Mass Commuication'), ('International Relations', 'International Relations'), ('Criminology', 'Criminology'), ('Language and Linguistics', 'Language and Linguistics')], default=None, max_length=100, verbose_name='Department'),
        ),
    ]
