# Generated by Django 3.1.6 on 2021-05-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_remove_student_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='image',
        ),
    ]
