# Generated by Django 3.1.6 on 2021-05-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0033_remove_exam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.CharField(default='', help_text='Must be all CAPS', max_length=20, verbose_name='Course'),
        ),
    ]
