# Generated by Django 3.1.6 on 2021-05-13 14:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0034_auto_20210512_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='instruction',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
