# Generated by Django 3.1.6 on 2021-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0035_auto_20210513_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, verbose_name='Course Code')),
                ('course_title', models.CharField(max_length=20, verbose_name='Course Title')),
            ],
            options={
                'verbose_name': 'Course Code',
                'verbose_name_plural': 'Course Code',
                'db_table': 'Course Code',
            },
        ),
    ]
