# Generated by Django 3.1.6 on 2021-05-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0036_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=100, verbose_name='Course Title'),
        ),
    ]
