# Generated by Django 3.1.6 on 2021-05-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_auto_20210513_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
