# Generated by Django 3.1.6 on 2021-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0038_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='exam_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
