# Generated by Django 3.1.6 on 2021-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_auto_20210514_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='exam_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
