# Generated by Django 3.1.6 on 2021-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0040_auto_20210514_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(default=None, max_length=10, verbose_name='Level'),
        ),
    ]
