# Generated by Django 3.1.6 on 2021-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0041_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Level'),
        ),
    ]
