# Generated by Django 3.1.6 on 2021-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0042_auto_20210516_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='level',
            field=models.CharField(default='', max_length=10, verbose_name='Level'),
        ),
    ]
