# Generated by Django 3.1.6 on 2021-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0043_paper_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], default='', max_length=15, verbose_name='Semester'),
        ),
    ]
