# Generated by Django 3.1.6 on 2021-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0045_auto_20210527_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='course',
            field=models.CharField(default='', error_messages={'unique': 'A user with that username already exists.'}, max_length=20, unique=True, verbose_name='Course'),
        ),
    ]
