# Generated by Django 3.1.6 on 2021-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0047_auto_20210529_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default='', max_length=10, verbose_name='Level'),
        ),
    ]
