# Generated by Django 3.1.6 on 2021-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0049_auto_20210529_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.CharField(default='', max_length=20, verbose_name='score'),
        ),
    ]
