# Generated by Django 3.1.6 on 2021-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0052_auto_20210531_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
