# Generated by Django 3.1.6 on 2021-05-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0054_auto_20210531_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='score',
        ),
    ]
