# Generated by Django 3.1.6 on 2021-06-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0056_grade_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='course_title',
            field=models.CharField(default='', max_length=100, verbose_name='Course Title'),
        ),
        migrations.AddField(
            model_name='paper',
            name='unit',
            field=models.IntegerField(default=1, verbose_name='Units'),
        ),
    ]
