# Generated by Django 3.1.6 on 2021-07-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0057_auto_20210619_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', error_messages={'unique': 'The Course has already been created, Add Questions!'}, max_length=20, unique=True, verbose_name='Course')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.teacher')),
            ],
            options={
                'verbose_name': 'Teacher course',
                'verbose_name_plural': 'Teacher course',
                'db_table': 'course',
            },
        ),
    ]
