# Generated by Django 3.1.6 on 2021-07-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0058_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Teacher Id'),
        ),
    ]
