# Generated by Django 3.1.6 on 2021-06-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='help-stand.jpg', upload_to='profile_pics'),
        ),
    ]
