# Generated by Django 3.1.6 on 2021-06-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0003_auto_20210601_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverimage',
            field=models.ImageField(default='default.png', upload_to='cover_pics'),
        ),
    ]
